### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by hawk66** [xaguzman/pathfinding#11]
The library is good and useable but currently there is no possibility to provide weights if I have not overseen sth?

**Comment by xaguzman** [comment]
can you please elaborate? Not sure what you are trying to do but you
can change the cost for orthogonal and diagonal movement in the
pathfinder options


On 7/15/16, hawk66 <notifications@github.com> wrote:
> The library is good and useable but currently there is no possibility to
> provide weights if I have not overseen sth?
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xaguzman/pathfinding/issues/11


-- 
---------------------------
*Xavier Guzman*

<http://blog.xavierguzman.com>
<http:////plus.google.com/u/0/113140404022814604923?>
<http://mx.linkedin.com/in/xavierguz/>       <https://twitter.com/arkalain>

Blog <http://blog.xavierguzman.com>   |  G+
<http:////plus.google.com/u/0/113140404022814604923?>  | LinkedIn
<http://mx.linkedin.com/in/xavierguz/> | Twitter
<https://twitter.com/arkalain>

**Comment by hawk66** [comment]
Ok, thx...I've missed that
