### ISSUE TITLE
Can't import from Gradle, but .jar works

### ISSUE THREAD

**Issue by JakeSteam** [xaguzman/pathfinding#14]
Hey,

Recently had an issue where I couldn't get the library to import successfully. Changing the version number to an invalid version 404'd, so it's some kind of configuration issue by the looks of it. Anyway, adding the jar worked.

![Error](https://cloud.githubusercontent.com/assets/12380876/22614554/5b828756-ea7b-11e6-841a-0ce02a984c47.png)

**Comment by xaguzman** [comment]
That's very weird...the pom file in maven central just shows the right dependency:

```xml
<dependency>
   <groupId>com.github.xaguzman</groupId>
   <artifactId>pathfinding</artifactId>
   <version>0.2.6</version>
   <scope>compile</scope>
</dependency>
```

Does it work if you reference the pathfinding dependency as well and not just the gdx bridge?

**Comment by JakeSteam** [comment]
Ahh, that explains it, I thought the GDX bridge was a fork, not an extension. No longer able to test, but that would explain it.
