### ISSUE TITLE
finder = new AStarGridFinder(GridCell.class) ERROR

### ISSUE THREAD

**Issue by francisco-javier** [xaguzman/pathfinding#15]
Hello, I am trying to use this library for a personal project of mine. Problem is that the line 
AStarGridFinder<GridCell> finder = new AStarGridFinder(GridCell.class);
makes the following exception
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.xguzm.pathfinding.BHeapNode;
Is there something I might be doing wrong?
Thank you.

**Comment by xaguzman** [comment]
Hello, not really.. everything looks good.

Is it possible for you to share the code so that I can take a look at it?
