### ISSUE TITLE
Is it possible to use this library to create an android app?

### ISSUE THREAD

**Issue by phfeitosaa** [xaguzman/pathfinding#16]
I need to create an android app from an internal map with internal navigation, using QR Codes to find the user's current location, and find the best path to the chosen destination in the application. Then show the map with the path and guide the user to the destination, like a GPS. I was looking for a library to help me create this app. Can yours be useful to me? And could you give me a handout on how I could use your library to develop this project for my college?

**Comment by xaguzman** [comment]
It is technically possible, You could make use of the finders, but you would need to create the graph yourself.

Basically, create an implementation for the interfaces NavigationGraph and NavigationNode.

After you assemble your graph, you should be able to use the astar finder to give you the shortest path.

**Comment by phfeitosaa** [comment]
Ok, I get it. How could I do that? Do you have any documentation or can you give me a brief explanation of how I create the graph? I do not have much experience with Android so I'm having a bit of trouble to implement. And do I need to use this GDX library or is it not necessary? Thank you very much in advance.

**Comment by xaguzman** [comment]
You do not need to use libgdx.

Also, I would advise downloading the source and checking NavigationGridGraph and NavigationGridCell for an implementation of these interfaces

**Comment by phfeitosaa** [comment]
OK. Thanks!
