### ISSUE TITLE
New tiled version

### ISSUE THREAD

**Issue by lucas-signorini** [xaguzman/pathfinding#19]
Hello, 

Once again, thanks for your project, its working like a charm.

I try to upgrade my libgdx version to 1.9.8, but i couldn't use like before. This libgdx version comes with a GroupMapLayer, to handle Groups in tiled (Also new versions). 
When your try to create a new NavigationTileMapLayer, i use as ((NavigationTiledMapLayer)  layer).getNodes(), it fails to cast. 
Specific message is: com.badlogic.gdx.maps.tiled.TiledMapTileLayer cannot be cast to org.xguzm.pathfinding.gdxbridge.NavigationTiledMapLayer

I have seen some previous issue where the name "navigation" is mandatory, so its not about that, my layer name is "navigation". If you just update libgdx version, it already fails to cast.

I can give more details if you need.

Dont know if im using it wrong or if something needs to be upgraded, just like to report it. 
Thanks!

**Comment by xaguzman** [comment]
Hello lucas,

are you using the [gdx-bridge](https://github.com/xaguzman/pathfinding/tree/master/gdx-bridge) extension and it's NavTmxMapLoader instead of Libgdx's default TmxMapLoader?

**Comment by lucas-signorini** [comment]
Hello,
Sorry for long time to reply.  Yes, im using gdx-bridge for that.
Gdx also uses now a TiledMapTileLayer (instead of MapLayer) that is not mapped yet by gdx-bridge, and also results in cast exception when you try to load.

Maybe updating the extends on the NavigationTiledMapLayer class should fix the problem.

Im trying to use libgdx 1.9.9

**Comment by xaguzman** [comment]
I totally forgot about this....
I am unable to take on this at the moment due to lack of time.
If anybody is willing to provide a PR it would be welcome, otherwise, It will need to wait until I find time

**Comment by lucas-signorini** [comment]
Hello. I manage to fix it. Also i made a change that make it able to be used with huge maps. The cache over current process on every cell used a huge amount of memory. As soon as i am sure about the changes and have the time i will try to make some pull requests. 

Great job again and thanks :D
