### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by xuanzhan12** [xaguzman/pathfinding#21]
Hi,

I just wanted to confirm that this library is under Apache License 2.0. I noticed there isn't a NOTICE or LICENSE file so I just wanted to make sure.
I'm looking to use your library in an app but not make any modifications.

**Comment by xaguzman** [comment]
Thanks for pointing it out.
I added the license file, and yes, it's APACHE 2.0 :)

**Comment by xuanzhan12** [comment]
Thanks a lot!
