### ISSUE TITLE
JumpPointFinder crashing when allowDiagonal is true

### ISSUE THREAD

**Issue by titoasty** [xaguzman/pathfinding#3]
JumpPointFinder is crashing when allowDiagonal is true.
I tried disabling diagonals and seems to work

**Comment by xaguzman** [comment]
Could you post your stacktrace and maybe provide a file with your graph set
up??

**Comment by titoasty** [comment]
I managed to make it working, and it was all my fault !
It was a bad initialization of GridCell, not passing column and row as parameters of the constructor.
And by the way, I think passing an array of GridCells to a NavigationGrid should automatically set the x and y of GridCells, don't you think ? It was kind of confusing...

But anyway, it's working fine ! (and I'm very glad you implemented jps, which is very fast, yours even seems faster than my implementation due to reutilization of objects. nice job on your library !)

**Comment by xaguzman** [comment]
I didn't have time to look into this, but I am glad you got it working, I was a bit insecure about the diagonals in JPS as it came out a bit hacky,

Also, good to see some people get benefits from using this lib :)
